---
- name: Configure VRRP Keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_conf }}"
    owner: root
    group: root
    mode: 0640
  with_items: front_end_ips
  notify: restart-keepalived